# Makefile for median_calculation extension

MODULES = median_calculation
EXTENSION = median_calculation
OBJS = median_calculation.o
DATA = median_calculation--0.0.1.sql

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
